POST http://localhost:5000/api/shortner
Content-Type: application/json

{
    "longUrl":"https://www.codegrepper.com/code-examples/sql/postgresql+add+days+to+date"
}

###

POST http://localhost:5000/api/modify
Content-Type: application/json

{
    "shortUrl":"https://habuild.in/dTqrZ_L5A",
    "days":"1"
}

###


GET http://localhost:5000/destination/dTqrZ_L5A
content-type: application/json
